name: planty_flutter_starter
description: Ein einfacher Planty Rezept-App Start für Flutter-Anfänger
version: 1.0.10+19

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  google_nav_bar: ^5.0.7

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.3

  drift: ^2.28.1
  sqlite3: ^2.9.0
  sqlite3_flutter_libs: ^0.5.39
  path: ^1.9.1
  path_provider: ^2.1.5
  csv: ^5.0.2   
  image_picker: ^1.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.28.1
  build_runner: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/ingredients/
    - assets/data/